apiVersion: v1
kind: Service
metadata:
  name: complaint-service
  namespace: dev
  labels:
    app: complaints
spec:
  selector:
    app: complaints
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9095
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: complaint-deployment
  namespace: dev
  labels:
    app: complaints
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: complaints
  template:
    metadata:
      labels:
        app: complaints
    spec:
      containers:
        - name: complaintmanager
          image: gcr.io/burner-prathakk1/complaint-service
          ports:
            - containerPort: 9095
          env:
          - name: DEPLOY_ENV
            value: default
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"